local NIX = require("nix-env")

-- Carichiamo i plugin tramite le API native
for _, plugin in ipairs(NIX.plugins) do
    hl.dispatch(hl.dsp.exec_cmd("hyprctl plugin load " .. plugin))
end

-- Caricamento automatico di tutti i file in lua/config/ a cascata
for _, mod in ipairs(NIX.configModules) do
    require("config." .. mod)
end

-- Configurazione globale
hl.config({
    autogenerated = false,
    
    general = {
        border_size = 2,
        gaps_in = 5,
        gaps_out = 10,
    },
    
    decoration = {
        rounding = 8,
    },
    
    cursor = {
        no_hardware_cursors = true,
    },
    
    env = {
        "WLR_NO_HARDWARE_CURSORS,1",
    }
})
