local NIX = require("nix-env")

-- 1. Inizializziamo i plugin e il debug prima di richiedere i moduli
hl.config({
    autogenerated = false,
    debug = {
        disable_logs = false,
    },
    plugin = NIX.plugins
})

-- 2. Caricamento automatico di tutti i file in lua/config/ a cascata
for _, mod in ipairs(NIX.configModules) do
    require("config." .. mod)
end

-- 3. Configurazione globale / Overrides
hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.env("WLR_NO_HARDWARE_CURSORS", "1")
