local NIX = require("nix-env")

hl.config({
    autogenerated = false,
    debug = {
        disable_logs = false,
    },
    plugin = NIX.plugins
})

for _, mod in ipairs(NIX.configModules) do
    require("." .. mod)
end

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.env("WLR_NO_HARDWARE_CURSORS", "1")
