-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


local mod = "ALT"

-- source = . /dms/colors.conf -> requires manual conversion
-- local colors = require("colors")
-- TODO: convert . /dms/colors.conf to .lua and use require()

hl.config({
    animations = {
        enabled = true,
    },
})

hl.bind(mod .. " + " .. "Return", hl.dsp.exec_cmd("alacritty"))

hl.bind("SUPER" .. " + " .. "W", hl.dsp.exec_cmd("brave"))

hl.bind("SUPER" .. " + " .. "F", hl.dsp.exec_cmd("nautilus"))

hl.bind("SUPER" .. " + " .. "B", hl.dsp.exec_cmd("dms ipc call notepad toggle"))

hl.bind("SUPER" .. " + " .. "C", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))

hl.bind("SUPER" .. " + " .. "P", hl.dsp.exec_cmd("keepassxc"))

hl.bind("SUPER" .. " + " .. "SUPER_L", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))

hl.bind(mod .. " + " .. "D", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))

hl.bind(mod .. " + " .. "M", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))

hl.bind(mod .. " + " .. "comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))

hl.bind(mod .. " + " .. "N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))

hl.bind(mod .. " + " .. "Y", hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))

hl.bind(mod .. " + " .. "TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

hl.bind("SUPER" .. " + " .. "K", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.dpms("toggle"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("hyprctl --batch dispatch togglefloating; dispatch resizeactive exact 40% 40%; dispatch moveactive exact 59% 58%"))

hl.bind(mod .. " + " .. "T", hl.dsp.layout("togglesplit"))

hl.bind(mod .. " + " .. "P", hl.dsp.window.pin())

hl.bind(mod .. " + " .. "O", hl.dsp.exec_cmd("hyprctl setprop active opaque toggle"))

hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot full"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot window"))

hl.bind(mod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "H", { direction = "l" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "L", { direction = "r" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "K", { direction = "u" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "J", { direction = "d" })

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.focus("l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.focus("r"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.focus("l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.focus("r"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.focus("u"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.focus("d"))

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "H", { direction = "mon:l" })

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "L", { direction = "mon:r" })

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "K", { direction = "mon:u" })

hl.bind(mod .. " + " .. "SHIFT + CTRL" .. " + " .. "J", { direction = "mon:d" })

hl.bind(mod .. " + " .. "Page_Down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "Page_Up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "U", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "I", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.move("e+1"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.move("e-1"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "U", hl.dsp.window.move("e+1"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "I", hl.dsp.window.move("e-1"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Page_Down", hl.dsp.window.move("e+1"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Page_Up", hl.dsp.window.move("e-1"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.window.move("e+1"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.window.move("e-1"))

hl.bind(mod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "mouse_down", hl.dsp.window.move("e+1"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "mouse_up", hl.dsp.window.move("e-1"))

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move(1))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move(2))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move(3))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move(4))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move(5))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move(6))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move(7))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move(8))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move(9))

hl.bind(mod .. " + " .. "bracketleft", hl.dsp.layout("preselect l"))

hl.bind(mod .. " + " .. "bracketright", hl.dsp.layout("preselect r"))

hl.bind(mod .. " + " .. "Home", hl.dsp.focus({ window = "first" }))

hl.bind(mod .. " + " .. "End", hl.dsp.focus({ window = "last" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprctl --batch dispatch setfloating; dispatch resizeactive exact 60% 60%; dispatch centerwindow; dispatch movetoworkspace special:scratch"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("hyprctl --batch dispatch movetoworkspace +0; dispatch settiled"))

hl.bind(mod .. " + " .. "S", hl.dsp.workspace.toggle_special("scratch"))

-- TODO: manual review (unknown dispatcher: Expand window left)
-- hl.bind("$mod + code:20", hl.dsp.Expand window left("resizeactive", "-100 0"))

-- TODO: manual review (unknown dispatcher: Shrink window left)
-- hl.bind("$mod + code:21", hl.dsp.Shrink window left("resizeactive", "100 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + minus", hl.dsp.resizeactive("-10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + equal", hl.dsp.resizeactive("10% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + SHIFT + minus", hl.dsp.resizeactive("0 -10%"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + SHIFT + equal", hl.dsp.resizeactive("0 10%"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:272", nil, { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })

hl.config({
    decoration = {
        blur = {
            enabled = true,
            new_optimizations = true,
            passes = 3,
            size = 3,
        },
        shadow = {
            color = "rgba(00000070)",
            enabled = false,
            offset = "0 5",
            range = 30,
            render_power = 5,
        },
        active_opacity = 0.950000,
        inactive_opacity = 0.800000,
        rounding = 12,
    },
})

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.env("SSH_AUTH_SOCK", "local_var_XDG_RUNTIME_DIR/gcr/ssh")







hl.config({
    general = {
        border_size = 2,
        gaps_in = 4,
        gaps_out = 8,
        layout = "dwindle",
    },
})

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

hl.config({
    input = {
        touchpad = {
            clickfinger_behavior = true,
            disable_while_typing = true,
            natural_scroll = true,
            scroll_factor = 0.500000,
            tap-to-click = true,
        },
        kb_layout = "it",
        kb_options = { "caps:escape", "shift:both_capslock" },
        numlock_by_default = true,
        sensitivity = 0,
    },
})

hl.config({
    master = {
        mfact = 0.500000,
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 0,
    },
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "3440x1440@100.00",
    position = "auto",
    scale    = 1.25,
})

hl.window_rule({
    name  = "no_anim_class___org_",
    match = {
    },
    -- TODO: review rule: "no_anim class:^(org.quickshell)$"
})

hl.window_rule({
    name  = "float_class___xdg-de",
    match = {
    },
    -- TODO: review rule: "float class:^(xdg-desktop-portal)(.*)$"
})

hl.window_rule({
    name  = "float_class___steam_",
    match = {
    },
    -- TODO: review rule: "float class:^(steam)$"
})

hl.window_rule({
    name  = "float_class___org_qu",
    match = {
    },
    -- TODO: review rule: "float class:^(org.quickshell)$"
})

hl.window_rule({
    name  = "float_class___bluema",
    match = {
    },
    -- TODO: review rule: "float class:^(blueman-manager)$"
})

hl.window_rule({
    name  = "float_class___zoom__",
    match = {
    },
    -- TODO: review rule: "float class:^(zoom)$"
})

-- -----------------------------------------------

-- RESIZE SUBMAP (i3 style)

-- -----------------------------------------------

hl.bind("ALT" .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + l", hl.dsp.resizeactive("100 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + h", hl.dsp.resizeactive("-100 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + k", hl.dsp.resizeactive("0 -100"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind(" + j", hl.dsp.resizeactive("0 100"))
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("return", hl.dsp.submap("reset"))
end)


-- -----------------------------------------------

-- PASSTHROUGH SUBMAP (per testare VM o Nested Wayland)

-- -----------------------------------------------

-- Attiva la modalità passthrough con CTRL + ALT + G (stile QEMU)

hl.bind("CTRL + ALT" .. " + " .. "G", hl.dsp.submap("passthru"))

-- Entriamo nella submap. Qui DENTRO, l'unica scorciatoia

-- riconosciuta dal sistema principale sarà quella per uscirne.

hl.define_submap("passthru", function()
    -- Premi di nuovo CTRL + ALT + G per sbloccare il sistema principale
    hl.bind("CTRL + ALT" .. " + " .. "G", hl.dsp.submap("reset"))
end)


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/nix/store/ai8mmqghspvnhv2jz12pfg6b6dqmg3b3-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
    --hl.exec_cmd("dms run")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("sleep 5 && dms ipc call plugins disable compactNetSpeedV8")
end)
